In [1]:
# Grayscale with ImageDataGenerator -70 epochs
#model-3

print('Importing the libraries')
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 
print('Part 1 - Data Preprocessing')

# Preprocessing the Training set
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

#train_datagen = ImageDataGenerator(rescale = 1./255)
training_set = train_datagen.flow_from_directory('train_set',
                                                 color_mode="grayscale",
                                                 target_size = (28, 28),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

# 
print('Preprocessing the Test set')
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('test_set',
                                            color_mode="grayscale",
                                            target_size = (28, 28),
                                            batch_size = 32,
                                            class_mode = 'categorical')


# 
print('Part 2 - Building the CNN')

# 
print('Initialising the CNN')
cnn = tf.keras.models.Sequential()

# 
print('Step 1 - Convolution')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(28, 28, 1)))

# 
print('Step 2 - Pooling')
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Adding a second convolutional layer')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Step 3 - Flattening')
cnn.add(tf.keras.layers.Flatten())

# 
print('Step 4 - Full Connection')
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# 
print('Step 5 - Output Layer')
cnn.add(tf.keras.layers.Dense(units=10, activation='softmax'))


# 
print('Part 3 - Training the CNN')

# 
print('Compiling the CNN')
opt = tf.keras.optimizers.Adam(learning_rate=1e-4)
cnn.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics = ["accuracy"])

# 
print('Training the CNN on the Training set and evaluating it on the Test set')
cnn.fit(x=training_set,validation_data=test_set, epochs=70)



cnn.save('model_grayscale_2.h5')
print("Saving the model as model_grayscale_2.h5")

Importing the libraries
Part 1 - Data Preprocessing
Found 9997 images belonging to 10 classes.
Preprocessing the Test set
Found 270 images belonging to 10 classes.
Part 2 - Building the CNN
Initialising the CNN
Step 1 - Convolution
Step 2 - Pooling
Adding a second convolutional layer
Step 3 - Flattening
Step 4 - Full Connection
Step 5 - Output Layer
Part 3 - Training the CNN
Compiling the CNN
Training the CNN on the Training set and evaluating it on the Test set
Epoch 1/70
313/313 [==============================] - 10s 30ms/step - loss: 2.2576 - accuracy: 0.2059 - val_loss: 2.2065 - val_accuracy: 0.3000
Epoch 2/70
313/313 [==============================] - ETA: 0s - loss: 1.9339 - accuracy: 0.4098 ETA - 9s 30ms/step - loss: 1.9319 - accuracy: 0.4101 - val_loss: 1.8684 - val_accuracy: 0.3815
Epoch 3/70
313/313 [==============================] - 9s 30ms/step - loss: 1.5217 - accuracy: 0.5239 - val_loss: 1.6676 - val_accuracy: 0.4926
Epoch 4/70
313/313 [==============================] - 9

Epoch 53/70
313/313 [==============================] - 9s 30ms/step - loss: 0.2788 - accuracy: 0.9132 - val_loss: 0.5404 - val_accuracy: 0.8370
Epoch 54/70
313/313 [==============================] - 10s 31ms/step - loss: 0.2764 - accuracy: 0.9157 - val_loss: 0.5320 - val_accuracy: 0.8481
Epoch 55/70
313/313 [==============================] - 10s 33ms/step - loss: 0.2736 - accuracy: 0.9160 - val_loss: 0.5476 - val_accuracy: 0.8222
Epoch 56/70
313/313 [==============================] - 10s 32ms/step - loss: 0.2707 - accuracy: 0.9161 - val_loss: 0.4958 - val_accuracy: 0.8407
Epoch 57/70
313/313 [==============================] - 10s 33ms/step - loss: 0.2599 - accuracy: 0.9205 - val_loss: 0.5180 - val_accuracy: 0.8296
Epoch 58/70
313/313 [==============================] - 10s 32ms/step - loss: 0.2579 - accuracy: 0.9215 - val_loss: 0.5206 - val_accuracy: 0.8407
Epoch 59/70
313/313 [==============================] - 10s 33ms/step - loss: 0.2558 - accuracy: 0.9215 - val_loss: 0.5586 - val_acc

In [2]:
from tensorflow.keras.models import load_model
import numpy as np
from tensorflow.keras.preprocessing import image
cnn=load_model('model_grayscale_2.h5')

In [3]:
test_image = image.load_img('1_156.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
test_image = image.load_img('9_86.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [5]:
test_image = image.load_img('two1.jfif', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
test_image = image.load_img('three.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
