In [55]:
# Grayscale with ImageDataGenerator- 60 epochs
#model-1

print('Importing the libraries')
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 
print('Part 1 - Data Preprocessing')

# Preprocessing the Training set
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

#train_datagen = ImageDataGenerator(rescale = 1./255)
training_set = train_datagen.flow_from_directory('train_set',
                                                 color_mode="grayscale",
                                                 target_size = (28, 28),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

# 
print('Preprocessing the Test set')
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('test_set',
                                            color_mode="grayscale",
                                            target_size = (28, 28),
                                            batch_size = 32,
                                            class_mode = 'categorical')


# 
print('Part 2 - Building the CNN')

# 
print('Initialising the CNN')
cnn = tf.keras.models.Sequential()

# 
print('Step 1 - Convolution')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(28, 28, 1)))

# 
print('Step 2 - Pooling')
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Adding a second convolutional layer')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Step 3 - Flattening')
cnn.add(tf.keras.layers.Flatten())

# 
print('Step 4 - Full Connection')
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# 
print('Step 5 - Output Layer')
cnn.add(tf.keras.layers.Dense(units=10, activation='softmax'))


# 
print('Part 3 - Training the CNN')

# 
print('Compiling the CNN')
opt = tf.keras.optimizers.Adam(learning_rate=1e-4)
cnn.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics = ["accuracy"])

# 
print('Training the CNN on the Training set and evaluating it on the Test set')
cnn.fit(x=training_set,validation_data=test_set, epochs=60)



cnn.save('model_grayscale_1.h5')
print("Saving the model as model_grayscale_1.h5")

Importing the libraries
Part 1 - Data Preprocessing
Found 9997 images belonging to 10 classes.
Preprocessing the Test set
Found 270 images belonging to 10 classes.
Part 2 - Building the CNN
Initialising the CNN
Step 1 - Convolution
Step 2 - Pooling
Adding a second convolutional layer
Step 3 - Flattening
Step 4 - Full Connection
Step 5 - Output Layer
Part 3 - Training the CNN
Compiling the CNN
Training the CNN on the Training set and evaluating it on the Test set
Epoch 1/60
313/313 [==============================] - 12s 36ms/step - loss: 2.2796 - accuracy: 0.1708 - val_loss: 2.2493 - val_accuracy: 0.17788 - accuracy - ETA: 0s - loss: 2.2803 - accuracy: 0.
Epoch 2/60
313/313 [==============================] - 10s 32ms/step - loss: 2.0383 - accuracy: 0.3686 - val_loss: 1.9472 - val_accuracy: 0.3407
Epoch 3/60
313/313 [==============================] - 9s 29ms/step - loss: 1.6183 - accuracy: 0.4900 - val_loss: 1.6705 - val_accuracy: 0.5000
Epoch 4/60
313/313 [==============================

313/313 [==============================] - 9s 30ms/step - loss: 0.2758 - accuracy: 0.9159 - val_loss: 0.5268 - val_accuracy: 0.8259
Epoch 54/60
313/313 [==============================] - 9s 30ms/step - loss: 0.2723 - accuracy: 0.9141 - val_loss: 0.5004 - val_accuracy: 0.8407
Epoch 55/60
313/313 [==============================] - 9s 30ms/step - loss: 0.2730 - accuracy: 0.9168 - val_loss: 0.4925 - val_accuracy: 0.8407
Epoch 56/60
313/313 [==============================] - 10s 31ms/step - loss: 0.2666 - accuracy: 0.9209 - val_loss: 0.4991 - val_accuracy: 0.8185
Epoch 57/60
313/313 [==============================] - 10s 31ms/step - loss: 0.2659 - accuracy: 0.9185 - val_loss: 0.4785 - val_accuracy: 0.8481
Epoch 58/60
313/313 [==============================] - 10s 31ms/step - loss: 0.2572 - accuracy: 0.9215 - val_loss: 0.5102 - val_accuracy: 0.8444
Epoch 59/60
313/313 [==============================] - 10s 31ms/step - loss: 0.2585 - accuracy: 0.9224 - val_loss: 0.4679 - val_accuracy: 0.8296


In [60]:
from tensorflow.keras.models import load_model
import numpy as np
from tensorflow.keras.preprocessing import image
cnn=load_model('model_grayscale_1.h5')

In [61]:
test_image = image.load_img('1_156.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [62]:
test_image = image.load_img('9_86.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [63]:
test_image = image.load_img('two1.jfif', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [64]:
test_image = image.load_img('three.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
