In [ ]:
# 
print('Importing the libraries')
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 
print('Part 1 - Data Preprocessing')

# Preprocessing the Training set
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

training_set = train_datagen.flow_from_directory('dataset1/train_set',
                                                 color_mode="grayscale",
                                                 target_size = (28, 28),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

# 
print('Preprocessing the Test set')
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('dataset1/test_set',
                                            color_mode="grayscale",
                                            target_size = (28, 28),
                                            batch_size = 32,
                                            class_mode = 'categorical')


# 
print('Part 2 - Building the CNN')

# 
print('Initialising the CNN')
cnn = tf.keras.models.Sequential()

# 
print('Step 1 - Convolution')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(28, 28, 1)))

# 
print('Step 2 - Pooling')
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Adding a second convolutional layer')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Step 3 - Flattening')
cnn.add(tf.keras.layers.Flatten())

# 
print('Step 4 - Full Connection')
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

cnn.add(tf.keras.layers.Dense(units=64, activation='relu'))

# 
print('Step 5 - Output Layer')
cnn.add(tf.keras.layers.Dense(units=10, activation='softmax'))


# 
print('Part 3 - Training the CNN')

# 
print('Compiling the CNN')
opt = tf.keras.optimizers.Adam(learning_rate=1e-4)
cnn.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics = ["accuracy"])

# 
print('Training the CNN on the Training set and evaluating it on the Test set')
cnn.fit(x=training_set,validation_data=test_set, epochs=5)



cnn.save('mnist.h5')
print("Saving the model as mnist1.h5")

In [2]:
# GRAYSCALE without ImageDataGenerate- 32 epochs
#model-3

print('Importing the libraries')
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 
print('Part 1 - Data Preprocessing')

# Preprocessing the Training set
train_datagen = ImageDataGenerator(rescale = 1./255)
'''
,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)'''

#train_datagen = ImageDataGenerator(rescale = 1./255)
training_set = train_datagen.flow_from_directory('train_set',
                                                 color_mode="grayscale",
                                                 target_size = (28, 28),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

# 
print('Preprocessing the Test set')
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('test_set',
                                            color_mode="grayscale",
                                            target_size = (28, 28),
                                            batch_size = 32,
                                            class_mode = 'categorical')


# 
print('Part 2 - Building the CNN')

# 
print('Initialising the CNN')
cnn = tf.keras.models.Sequential()

# 
print('Step 1 - Convolution')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu', input_shape=(28, 28, 1)))

# 
print('Step 2 - Pooling')
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Adding a second convolutional layer')
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

# 
print('Step 3 - Flattening')
cnn.add(tf.keras.layers.Flatten())

# 
print('Step 4 - Full Connection')
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

# 
print('Step 5 - Output Layer')
cnn.add(tf.keras.layers.Dense(units=10, activation='softmax'))


# 
print('Part 3 - Training the CNN')

# 
print('Compiling the CNN')
opt = tf.keras.optimizers.Adam(learning_rate=1e-4)
cnn.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics = ["accuracy"])

# 
print('Training the CNN on the Training set and evaluating it on the Test set')
cnn.fit(x=training_set,validation_data=test_set, epochs=32)



cnn.save('model_grayscale_3.h5')
print("Saving the model as model_grayscale_3.h5")

Importing the libraries
Part 1 - Data Preprocessing
Found 9997 images belonging to 10 classes.
Preprocessing the Test set
Found 270 images belonging to 10 classes.
Part 2 - Building the CNN
Initialising the CNN
Step 1 - Convolution
Step 2 - Pooling
Adding a second convolutional layer
Step 3 - Flattening
Step 4 - Full Connection
Step 5 - Output Layer
Part 3 - Training the CNN
Compiling the CNN
Training the CNN on the Training set and evaluating it on the Test set
Epoch 1/32
313/313 [==============================] - 8s 24ms/step - loss: 2.1813 - accuracy: 0.3101 - val_loss: 1.9307 - val_accuracy: 0.4778
Epoch 2/32
313/313 [==============================] - 7s 24ms/step - loss: 1.3739 - accuracy: 0.6158 - val_loss: 1.3773 - val_accuracy: 0.5519
Epoch 3/32
313/313 [==============================] - 7s 22ms/step - loss: 0.9802 - accuracy: 0.7049 - val_loss: 1.2099 - val_accuracy: 0.6481
Epoch 4/32
313/313 [==============================] - 7s 21ms/step - loss: 0.8420 - accuracy: 0.7450 - v

In [3]:
from tensorflow.keras.models import load_model
import numpy as np
from tensorflow.keras.preprocessing import image
cnn=load_model('model_grayscale_3.h5')

In [4]:
test_image = image.load_img('1_156.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
test_image = image.load_img('9_86.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [9]:
test_image = image.load_img('two1.jfif', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
test_image = image.load_img('three.jpg', target_size = (28,28))
test_image=test_image.convert('L')
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image)
training_set.class_indices
print(result)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
